# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FWnHQCA1dxCOtsm5ZpFSKqLZq42Q4wDd
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score

url = "https://docs.google.com/spreadsheets/d/1ay2nOuofGz3xPcndKkR--hStjd7iHCN4EPAQsyNi6E8/export?format=csv&gid=0"
df = pd.read_csv(url)

X = df[['tamanho_m2', 'quartos', 'banheiros', 'vagas_garagem', 'distancia_centro_km', 'renda_media_regiao']]
y = df['bairro_classe']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

knn = KNeighborsClassifier(n_neighbors=5) #Melhor Acuracia
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

print(f"Acurácia: {accuracy_score(y_test, y_pred):.2%}")
print("\nRelatório de Classificação:")
print(classification_report(y_test, y_pred))