# -*- coding: utf-8 -*-
"""Naive.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJ9MVqBO1EBOH0Plud3QnykPPS3y62U7
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, accuracy_score

url = "https://docs.google.com/spreadsheets/d/1ay2nOuofGz3xPcndKkR--hStjd7iHCN4EPAQsyNi6E8/export?format=csv&gid=0"
df = pd.read_csv(url)

X = df[['tamanho_m2', 'quartos', 'banheiros', 'vagas_garagem', 'distancia_centro_km', 'renda_media_regiao']]
y = df['bairro_classe']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

naive_model = GaussianNB()
naive_model.fit(X_train, y_train)

y_pred = naive_model.predict(X_test)

print(f"Acurácia Naive Bayes: {accuracy_score(y_test, y_pred):.2%}")
print("\nRelatório de Classificação (Naive Bayes):")
print(classification_report(y_test, y_pred))