# -*- coding: utf-8 -*-
"""Regras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vIhQ8VikO6F0hSkSh8trllC8JN_hUsvF
"""

!pip install wittgenstein

import pandas as pd
import wittgenstein as lw
from sklearn.model_selection import train_test_split

url = "https://docs.google.com/spreadsheets/d/1ay2nOuofGz3xPcndKkR--hStjd7iHCN4EPAQsyNi6E8/export?format=csv&gid=0"
df = pd.read_csv(url)

df.columns = df.columns.str.strip()
print("Colunas encontradas no arquivo:", list(df.columns))

FEATURES = ['tamanho_m2', 'quartos', 'banheiros', 'vagas_garagem', 'distancia_centro_km', 'renda_media_regiao']
TARGET = 'bairro_classe'

if TARGET not in df.columns:
    print(f"ERRO: A coluna '{TARGET}' não foi encontrada!")
else:
    X = df[FEATURES]
    y = df[TARGET]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    ripper = lw.RIPPER(random_state=42)
    ripper.fit(X_train, y_train)

    print("\n=== ALGORITMO DE REGRAS (RIPPER) ===")
    print(f"Acurácia: {ripper.score(X_test, y_test):.2%}")

    print("\n=== CONJUNTO DE REGRAS ENCONTRADAS ===")
    for rule in ripper.ruleset_:
        print(rule)

